function [newData1] = importfile1(fileToRead1)
%IMPORTFILE1(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 03-Dec-2015 17:18:09

% Import the file
sheetName='phi (4)';
[numbers, strings] = xlsread('PLDT', sheetName);
if ~isempty(numbers)
    newData1.data =  numbers;
end
if ~isempty(strings)
    newData1.textdata =  strings;
end

